#!/usr/bin/env sh

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Vim
alias vim=nvim
alias v=nvim

# Get fastest mirrors in Arch
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
# In Manjaro
alias update="sudo pacman-mirrors -f 5 && sudo pacman -Syyu"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# Confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Access Zsh's dir stack
alias d='. dirstack'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# Adding flags
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias lynx='lynx -cfg=~/.lynx/lynx.cfg -lss=~/.lynx/lynx.lss -vikeys'
alias vifm='./.config/vifm/scripts/vifmrun'
alias ncmpcpp='ncmpcpp ncmpcpp_directory=$HOME/.config/ncmpcpp/'
alias mocp='mocp -M "$XDG_CONFIG_HOME"/moc -O MOCDir="$XDG_CONFIG_HOME"/moc'
alias bat='bat --theme="base16-256"'

# GPG encryption
# Verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# Receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"
#
# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Kubectl
alias k="kubectl"

# Get top process eating cpu 
alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
alias psmem='ps auxf | sort -nr -k 4 | head -5'
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# Get error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# Better ls
alias ls="eza --icons --git" #ls
alias ll="eza -l --icons --group --git -a" #ls -lah"
alias lt="eza -l --sort=modified --group --icons --git -a" #ls -latrh"

# Git
alias ga="git a"
alias gs="git s"
alias gls="git ls"
alias glg="git lg"
alias gll="git ll"
alias gld="git ld"
alias glds="git lds"
alias gcm="git cm"
alias gco="git co"
alias gp="git p"
alias gpp="git pp"

case "$(uname -s)" in
    Darwin)
        alias ls='ls -G'
        ;;

    Linux)
        # alias ls='ls --color=auto'
        ;;

    CYGWIN* | MINGW32* | MSYS* | MINGW*)
        # 'MS Windows'
        ;;
    *)
        # 'Other OS'
        ;;
esac
