#!/usr/bin/env sh

HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

# PATH
if [ -d "$HOME/go" ]; then
  export GOPATH=$HOME/go
  PATH="$(go env GOPATH)/bin:$PATH"
fi

### PATH
if [ -d "$HOME/.luarocks/bin" ]; then
  PATH="$HOME/.luarocks/bin:$PATH"
fi

if [ -d "$HOME/.bin" ]; then 
  PATH="$HOME/.bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ]; then
  PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/Applications" ]; then
  PATH="$HOME/Applications:$PATH"
fi

if [ -d "$HOME/.cargo/bin" ]; then
  PATH="$HOME/.cargo/bin:$PATH"
fi

if [ -d "$HOME/.yarn/bin" ]; then
  PATH="$HOME/.yarn/bin:$PATH"
fi

if [ -d "$HOME/.yarn/bin" ]; then
  PATH="/opt/clang-format-static:$PATH"
fi

export PATH=$PATH

# export MANPAGER='nvim +Man!'
export MANPAGER="sh -c 'col -bx | bat --theme=\"base16-256\" -l man -p'"
export MANWIDTH=999

export TERM="xterm-256color"
# export HISTORY_IGNORE="(ls|cd|pwd|exit|sudo reboot|history|cd -|cd ..)"
export EDITOR="nvim"
export VISUAL="nvim"

# SSH Agent stuff
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# eval "`pip completion --zsh`"

case "$(uname -s)" in
Darwin)
    export GOARCH=arm64
	;;

Linux)
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# 'MS Windows'
	;;
*)
	# 'Other OS'
	;;
esac
