#!/usr/bin/env sh

# --------------------------------------------------------------------------------------- Functions
source "$ZDOTDIR/zsh-functions"

# -------------------------------------------------------------------- Zsh options (man zshoptions)
setopt autocd extendedglob nomatch complete_in_word appendhistory #menucomplete
setopt interactive_comments
stty stop undef		       # Disable ctrl-s to freeze terminal.
# zle_highlight=('paste:none')

setopt AUTO_PUSHD              # Push the current directory visited on the stack
setopt PUSHD_IGNORE_DUPS       # Do not store duplicates in the stack
setopt PUSHD_SILENT            # Do not print the directory stack after pushd or popd

unsetopt BEEP
unsetopt beep

# ------------------------------------------------------------------------------------- Completions
zmodload zsh/complist
# Load the compinit function from the compinit file in Zsh search path; then call it; 
# The function is lazy-loaded
#   -U - don't expand aliases
autoload -Uz compinit; compinit
_comp_options+=(globdots) # Include hidden files

# needs to be loaded after compinit, but before plugins which will wrap widgets,
# such as zsh-autosuggestions or fast-syntax-highlighting
zsh_add_plugin "Aloxaf/fzf-tab"

source "$ZDOTDIR/completion/custom-completion.zsh"
zsh_add_completion "esc/conda-zsh-completion" false
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions
if [[ ":$FPATH:" != *":/home/lukefilewalker/.config/zsh/completions:"* ]]; then export FPATH="/home/lukefilewalker/.config/zsh/completions:$FPATH"; fi

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
zle -N fzf_dirs_widget

# Colors
autoload -Uz colors && colors

# Edit command in editor with "v" in Vim normal mode
# autoload -Uz edit-command-line
# zle -N edit-command-line
# bindkey -M vicmd v edit-command-line

# ----------------------------------------------------------------------------------------- Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "romkatv/powerlevel10k"
zsh_add_plugin "zap-zsh/fzf"
zsh_add_plugin "zsh-users/zsh-completions"
# zsh_add_plugin "jeffreytse/zsh-vi-mode"
# zsh_add_plugin "Tarrasch/zsh-bd"
# zsh_add_plugin "Freed-Wu/fzf-tab-source"

# ----------------------------------------------------------------------------------------- Imports
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-private"

# ------------------------------------------------------------------------------------ Key-bindings
bindkey -s '^o' 'ranger^M'
bindkey -s '^s' 'ncdu^M'
# bindkey -s '^v' 'nvim $(fzf)^M'
bindkey '^[[P' delete-char
bindkey "^p" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey "^k" up-line-or-beginning-search # Up
bindkey "^j" down-line-or-beginning-search # Down
bindkey -r "^u"
bindkey -r "^d"
bindkey '\e[1;6T' fzf_dirs_widget

### Change title of terminals
case ${TERM} in
    xterm*|rxvt*|Eterm*|aterm|kterm|gnome*|alacritty|st|kitty|konsole*)
        PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
        ;;
    screen*)
        PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
        ;;
esac

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
# bindkey '^e' edit-command-line

run_cmd "fastfetch" "-c" "$HOME/.config/fastfetch/config.jsonc"

# ----------------------------------------------------------------------------------- Powerlevel10k
source "$ZDOTDIR/zsh-prompt"
