#! /usr/bin/env bash

#### VARIABLES ####

host=$(hostname)

#### AUTOSTART ####

if [[ "$host" == "samurai" ]]
then
    xrandr --output DVI-D-0 --left-of DP-0 --output HDMI-0 --right-of DP-0
    sxhkd &
else
    sxhkd -c /home/dief/.config/sxhkd/sxhkdrc.shinobi &
fi

nitrogen --restore &
sleep 1; compton -b
~/.config/wpg/wp_init.sh
/home/dief/.config/polybar/launch.sh &
nm-applet &
blueman-applet &
xautolock -time 10 -locker /home/dief/.local/bin/lock &
#ff-theme-util &
#fix_xcursor &
/home/dief/.local/share/tresorit/tresorit --hidden &

if [[ "$host" == "shinobi" ]]
then
    cbatticon &
    pasystray &
    #amixer set Capture toggle
fi

if [[ "$host" == "samurai" ]]
then
    pamac-tray &
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    start_conky_maia &
    volumeicon &
    clipit &
fi

#### AUTOSTART and place on desktop ####

if [[ "$host" == "samurai" ]]
then
    bspc rule -a st-256color -o desktop=^1 && st /home/dief/.local/bin/vagrant-up &
    bspc rule -a Slack -o desktop=^2 && slack &
    bspc rule -a Brave-browser -o desktop=^6 && brave &
    bspc rule -a Chromium -o desktop=^11 && chromium &
fi
bspc rule -a Google-chrome -o desktop=^3 && google-chrome-stable &

#### MONITORS ####

if [[ "$host" == "samurai" ]]
then
    bspc monitor DVI-D-0 -d 1 2 3 4 5
    bspc monitor DP-0 -d 6 7 8 9
    bspc monitor HDMI-0 -d 10 11 12 13 14
elif [[ "$host" == "shinobi" ]]
then
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
else
    bspc monitor default -d 1 2 3 4 5 6 7 8 9 0
fi

#### BSPWM configuration ####

#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####

bspc config normal_border_color		"#2E3440" #"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

#bspc rule -a Gimp state=floating follow=on
bspc rule -a Slack desktop='^2'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a Brave-browser desktop='^4'
bspc rule -a mplayer2 state=floating
if [[ "$host" == "samurai" ]]
then
    bspc rule -a Chromium state=floating
fi
bspc rule -a TorGuard state=floating
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### setxkbmap commands ####
setxkbmap -option caps:backspace
setxkbmap -option compose:ralt
