#!/usr/bin/env bash

LPATH="$(
	cd "$(dirname "$0")"
	pwd -P
)"

note=$(rofi -theme "$LPATH/rasi/wide.rasi" -dmenu -p "Note to add:")

if [ -n "$note" ]; then
	token=$(cat ~/.obs-tok)
	curl -k \
		-H "Content-Type: text/markdown" \
		-H "Authorization: Bearer $token" \
		-X POST "https://localhost:27124/vault/inbox.md" \
		--data "- $note"
fi

