#!/usr/bin/env bash

LPATH="$(
	cd "$(dirname "$0")"
	pwd -P
)"

inbox_file="$HOME/repos/notes/inbox.md"
note=$(rofi -theme "$LPATH/rasi/wide.rasi" -dmenu -p "Note to add:")

if [ -n "$note" ]; then
	echo "- [ ] $note ($(date))" >> $HOME/repos/notes/inbox.md
fi

