#!/usr/bin/env bash

SCRIPTPATH="$(
	cd "$(dirname "$0")"
	pwd -P
)"

# Set background
if [ -x "$(command -v feh)" ]; then
	feh --bg-fill $SCRIPTPATH/down.jpg
fi

leftwm-command "UnloadTheme"

pkill dunst
pkill picom
pkill polybar
pkill nm-applet
pkill pamac-tray
pkill xfce4-notifyd
