#!/usr/bin/env bash

vpn_connected=$(nmcli con show --active | rg "(wireguard|juniper|vpn)")
if [[ ! -z $vpn_connected ]]; then
	echo "[󰖂 $(echo $vpn_connected | awk '{print $1}')]"
else
	echo "[-_-]"
fi
