#!/bin/bash

LPATH="$(
	cd "$(dirname "$0")"
	pwd -P
)"

rofi_cmd="rofi -theme $LPATH/rasi/base.rasi"

msg_header="Network Management"

notify-send -t 1000 -a "$msg_header" "Getting VPNs..."

networks=$(nmcli con | rg "(wireguard|juniper|vpn)")
num_networks=$(echo "$networks" | wc -l)
theme_str="listview {lines: $num_networks;}"
chosen_network=$(echo "$networks" | $rofi_cmd -dmenu -theme-str "$theme_str" -p "VPN:")
chosen_network=$(echo "$chosen_network" | awk '{print $1}')

if [[ -z $chosen_network ]]; then
	exit 1
fi

active_vpn=$(nmcli con show --active | rg "(wireguard|juniper|vpn)")

if [[ -z $active_vpn ]]; then
	res=$(nmcli connection up id $chosen_network)
else
	res=$(nmcli connection down id $chosen_network)
fi

notify-send -t 1000 -a $msg_header "$(echo $res | sed 's/(.*$//')"
