#!/bin/bash

msg_header="Network Management"

notify-send -t 1000 -a "$msg_header" "Getting WiFi networks..."

theme=$HOME/.config/rofi/launchers/type-1/style-5.rasi

chosen_network=$(nmcli -g SSID device wifi | rofi -dmenu -i -p "Wifi network" -no-custom -theme "$theme")

if [[ -z $chosen_network ]]
then
    exit 1
fi

if [[ -n $(nmcli -g NAME connection | grep $chosen_network) ]]; then
    nmcli connection up id $chosen_network
else
    nmcli device wifi connect $chosen_network
fi
