return {
  'm4xshen/hardtime.nvim',
  event = 'VeryLazy',
  dependencies = { 'MunifTanjim/nui.nvim', 'nvim-lua/plenary.nvim' },
  opts = {
    max_time = 750,
    disable_mouse = false,
    disabled_filetypes = {
      'NvimTree',
      'TelescopePrompt',
      'aerial',
      'alpha',
      'checkhealth',
      'dapui*',
      'Diffview*',
      'Dressing*',
      'help',
      'httpResult',
      'lazy',
      'Neogit*',
      'mason',
      'neotest-summary',
      'minifiles',
      'neo*',
      'netrw',
      'noice',
      'notify',
      'prompt',
      'qf',
      'oil',
      'undotree',
      'fugitive',
    },
    disabled_keys = {
      ['<Up>'] = { '', 'i' },
      ['<Down>'] = { '', 'i' },
      ['<Left>'] = { '', 'i' },
      ['<Right>'] = { '', 'i' },
    },
  },
}
